### ISSUE TITLE
How to make start date from Monday to sunday ?

### ISSUE THREAD

**Issue by supriya-rajen** [Sach16/swipedate-calendar#1]

**Comment by Sach16** [comment]
If you can please elaborate the question or give me a hint over the functionality then would be able to answer your query. Thanks!

**Comment by supriya-rajen** [comment]
in this screen shot,day of the week starts from Sunday,Monday...Saturday, what i want is to start from Monday ,Tuesday,,,Sunday,

![9sctq](https://user-images.githubusercontent.com/16940872/27582737-a8750f44-5b4f-11e7-9c47-9bf60e2f35be.png)

this what i want, i dono where to change

**Comment by Sach16** [comment]
If you have referred my code. I have created the instance of GregorianCalendar. Use that instance and set your preferred first day.
```
GregorianCalendar cal = new GregorianCalendar(year, month, day);
            cal.setFirstDayOfWeek(Calendar.MONDAY); //Set whichever day required.
```

**Comment by supriya-rajen** [comment]
I have done what u mentioned  above, but still i not getting. Where i have changed is, 

 GregorianCalendar cal = new GregorianCalendar(yy, lCurrentMonth, 1);
cal.setFirstDayOfWeek(Calendar.MONDAY);

in **CalenderActivity** in your code.

**Comment by Sach16** [comment]
Just tried compiling and running my code.

`GregorianCalendar cal = new GregorianCalendar(yy, currentMonth, 1); // changing the value to 0 - starts day from monday changing the value to 1 - starts day from sunday and so on..`

This is working like a charm for me. Please check and upvote my answer at [custom-calendar-date-range-swipe-selection-android](https://stackoverflow.com/questions/36128738/custom-calendar-date-range-swipe-selection-android)
